production:
  adapter: postgresql
  database: unicorn_factory_development
  host: localhost

development:
  adapter: postgresql
  database: unicorn_factory_development
  host: localhost

test:
  adapter: postgresql
  database: unicorn_factory_test
  host: localhost